const fs = require('fs-extra');

const plugins = [
  // Demo files
  ['resources/js/demo/', 'public/assets/js/demo/'],

  // Plugins
  ['node_modules/@fortawesome', 'public/assets/plugins/@fortawesome'],
  ['node_modules/@fullcalendar', 'public/assets/plugins/@fullcalendar'],
  ['node_modules/@highlightjs', 'public/assets/plugins/@highlightjs'],
  ['node_modules/abpetkov-powerange', 'public/assets/plugins/abpetkov-powerange'],
  ['node_modules/angular', 'public/assets/plugins/angular'],
  ['node_modules/angular-ui-bootstrap', 'public/assets/plugins/angular-ui-bootstrap'],
  ['node_modules/angular-ui-router', 'public/assets/plugins/angular-ui-router'],
  ['node_modules/animate.css', 'public/assets/plugins/animate.css'],
  ['node_modules/apexcharts', 'public/assets/plugins/apexcharts'],
  ['node_modules/blueimp-file-upload', 'public/assets/plugins/blueimp-file-upload'],
  ['node_modules/blueimp-gallery', 'public/assets/plugins/blueimp-gallery'],
  ['node_modules/blueimp-canvas-to-blob', 'public/assets/plugins/blueimp-canvas-to-blob'],
  ['node_modules/blueimp-load-image', 'public/assets/plugins/blueimp-load-image'],
  ['node_modules/blueimp-tmpl', 'public/assets/plugins/blueimp-tmpl'],
  ['node_modules/bootstrap', 'public/assets/plugins/bootstrap'],
  ['node_modules/bootstrap-datepicker', 'public/assets/plugins/bootstrap-datepicker'],
  ['node_modules/bootstrap-daterangepicker', 'public/assets/plugins/bootstrap-daterangepicker'],
  ['node_modules/bootstrap-datetime-picker', 'public/assets/plugins/bootstrap-datetime-picker'],
  ['node_modules/bootstrap-icons', 'public/assets/plugins/bootstrap-icons'],
  ['node_modules/bootstrap-social', 'public/assets/plugins/bootstrap-social'],
  ['node_modules/bootstrap-timepicker', 'public/assets/plugins/bootstrap-timepicker'],
  ['node_modules/bootstrap3-wysihtml5-bower', 'public/assets/plugins/bootstrap3-wysihtml5-bower'],
  ['node_modules/chart.js', 'public/assets/plugins/chart.js'],
  ['node_modules/clipboard', 'public/assets/plugins/clipboard'],
  ['node_modules/d3', 'public/assets/plugins/d3'],
  ['node_modules/datatables.net', 'public/assets/plugins/datatables.net'],
  ['node_modules/datatables.net-autofill', 'public/assets/plugins/datatables.net-autofill'],
  ['node_modules/datatables.net-autofill-bs5', 'public/assets/plugins/datatables.net-autofill-bs5'],
  ['node_modules/datatables.net-bs5', 'public/assets/plugins/datatables.net-bs5'],
  ['node_modules/datatables.net-buttons', 'public/assets/plugins/datatables.net-buttons'],
  ['node_modules/datatables.net-buttons-bs5', 'public/assets/plugins/datatables.net-buttons-bs5'],
  ['node_modules/datatables.net-colreorder', 'public/assets/plugins/datatables.net-colreorder'],
  ['node_modules/datatables.net-colreorder-bs5', 'public/assets/plugins/datatables.net-colreorder-bs5'],
  ['node_modules/datatables.net-fixedcolumns', 'public/assets/plugins/datatables.net-fixedcolumns'],
  ['node_modules/datatables.net-fixedcolumns-bs5', 'public/assets/plugins/datatables.net-fixedcolumns-bs5'],
  ['node_modules/datatables.net-fixedheader', 'public/assets/plugins/datatables.net-fixedheader'],
  ['node_modules/datatables.net-fixedheader-bs5', 'public/assets/plugins/datatables.net-fixedheader-bs5'],
  ['node_modules/datatables.net-keytable', 'public/assets/plugins/datatables.net-keytable'],
  ['node_modules/datatables.net-keytable-bs5', 'public/assets/plugins/datatables.net-keytable-bs5'],
  ['node_modules/datatables.net-responsive', 'public/assets/plugins/datatables.net-responsive'],
  ['node_modules/datatables.net-responsive-bs5', 'public/assets/plugins/datatables.net-responsive-bs5'],
  ['node_modules/datatables.net-rowreorder', 'public/assets/plugins/datatables.net-rowreorder'],
  ['node_modules/datatables.net-rowreorder-bs5', 'public/assets/plugins/datatables.net-rowreorder-bs5'],
  ['node_modules/datatables.net-scroller', 'public/assets/plugins/datatables.net-scroller'],
  ['node_modules/datatables.net-scroller-bs5', 'public/assets/plugins/datatables.net-scroller-bs5'],
  ['node_modules/datatables.net-select', 'public/assets/plugins/datatables.net-select'],
  ['node_modules/datatables.net-select-bs5', 'public/assets/plugins/datatables.net-select-bs5'],
  ['node_modules/datepickk', 'public/assets/plugins/datepickk'],
  ['node_modules/dropzone', 'public/assets/plugins/dropzone'],
  ['node_modules/flag-icons', 'public/assets/plugins/flag-icons'],
  ['node_modules/flot', 'public/assets/plugins/flot'],
  ['node_modules/gritter', 'public/assets/plugins/gritter'],
  ['node_modules/intro.js', 'public/assets/plugins/intro.js'],
  ['node_modules/ion-rangeslider', 'public/assets/plugins/ion-rangeslider'],
  ['node_modules/ionicons', 'public/assets/plugins/ionicons'],
  ['node_modules/isotope-layout', 'public/assets/plugins/isotope-layout'],
  ['node_modules/jquery', 'public/assets/plugins/jquery'],
  ['node_modules/jquery-knob', 'public/assets/plugins/jquery-knob'],
  ['node_modules/jquery-migrate', 'public/assets/plugins/jquery-migrate'],
  ['node_modules/jquery-mockjax', 'public/assets/plugins/jquery-mockjax'],
  ['node_modules/jquery-sparkline', 'public/assets/plugins/jquery-sparkline'],
  ['node_modules/jquery-ui-dist', 'public/assets/plugins/jquery-ui-dist'],
  ['node_modules/jquery.maskedinput', 'public/assets/plugins/jquery.maskedinput'],
  ['node_modules/js-cookie', 'public/assets/plugins/js-cookie'],
  ['node_modules/jstree', 'public/assets/plugins/jstree'],
  ['node_modules/jszip', 'public/assets/plugins/jszip'],
  ['node_modules/jvectormap-content', 'public/assets/plugins/jvectormap-content'],
  ['node_modules/jvectormap-next', 'public/assets/plugins/jvectormap-next'],
  ['node_modules/kbw-countdown', 'public/assets/plugins/kbw-countdown'],
  ['node_modules/lightbox2', 'public/assets/plugins/lightbox2'],
  ['node_modules/lity', 'public/assets/plugins/lity'],
  ['node_modules/masonry-layout', 'public/assets/plugins/masonry-layout'],
  ['node_modules/moment', 'public/assets/plugins/moment'],
  ['node_modules/nvd3', 'public/assets/plugins/nvd3'],
  ['node_modules/oclazyload', 'public/assets/plugins/oclazyload'],
  ['node_modules/oclazyload', 'public/assets/plugins/oclazyload'],
  ['node_modules/pace-js', 'public/assets/plugins/pace-js'],
  ['node_modules/parsleyjs', 'public/assets/plugins/parsleyjs'],
  ['node_modules/pdfmake', 'public/assets/plugins/pdfmake'],
  ['node_modules/perfect-scrollbar', 'public/assets/plugins/perfect-scrollbar'],
  ['node_modules/photoswipe', 'public/assets/plugins/photoswipe'],
  ['node_modules/quill', 'public/assets/plugins/quill'],
  ['node_modules/raphael', 'public/assets/plugins/raphael'],
  ['node_modules/select-picker', 'public/assets/plugins/select-picker'],
  ['node_modules/select2', 'public/assets/plugins/select2'],
  ['node_modules/simple-line-icons', 'public/assets/plugins/simple-line-icons'],
  ['node_modules/spectrum-colorpicker2', 'public/assets/plugins/spectrum-colorpicker2'],
  ['node_modules/summernote', 'public/assets/plugins/summernote'],
  ['node_modules/sweetalert', 'public/assets/plugins/sweetalert'],
  ['node_modules/swiper', 'public/assets/plugins/swiper'],
  ['node_modules/switchery', 'public/assets/plugins/switchery'],
  ['node_modules/tag-it', 'public/assets/plugins/tag-it'],
  ['node_modules/x-editable-bs4', 'public/assets/plugins/x-editable-bs4']
];
plugins.forEach(([src, dest]) => {
  try {
    fs.copySync(src, dest);
    console.log(`✅ Copied: ${src} → ${dest}`);
  } catch (error) {
    console.error(`❌ Failed to copy: ${src}`);
    console.error(error.message);
  }
});